nelmio_api_doc:
    documentation:
        info:
            title: autoresDemo
            description: Demo de la app para la tesis
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/(doc|doc.json)$) # Accepts routes under /api except /api/doc
