security:
    encoders:
        App\Entity\User:
            algorithm: sha512

    providers:
        api_user_provider:
            entity:
                class: App\Entity\Usuario
                property: email

    firewalls:
        oauth_token:
            pattern: ^/api/oauth/v2/token
            security: false
            access_denied_handler: App\Security\AccessDeniedHandler

        public_api:
            pattern: ^/api/v1.0/public
            stateless: true
            anonymous: true
            
        api:
            pattern: ^/api/v1.0
            stateless: true
            anonymous: false
            provider: api_user_provider
            fos_oauth: true
