#index:
#    path: /
#    controller: App\Controller\DefaultController::index
v1_controllers:
    resource: ../src/Controller/v1
    type: annotation
    prefix: '/api/v1.0'
auth_controllers:
    resource: ../src/Controller/auth
    type: annotation
    prefix: '/api'

v1_public_controllers:
    resource: ../src/Controller/v1/pub
    type: annotation
    prefix: '/api/v1.0/public'
